### ISSUE TITLE
Cross-Architecture ISO Build Workflow: Unrecognized matrix.architecture in Certain Steps

### ISSUE THREAD

**Issue by SoftwareRat** [SoftwareRat/pppwn_live#1]
I encountered an issue with my GitHub Actions workflow for building cross-architecture ISO images. The `matrix.architecture` variable is not being recognized in some steps, leading to the following error:

```
Unrecognized named-value: 'matrix'. Located at position 1 within expression: matrix.architecture
```

### Error Details:

- **File**: `.github/workflows/ci.yaml`
- **Line**: 47 (and 61)
- **Error**: 
  ```
  Unrecognized named-value: 'matrix'. Located at position 1 within expression: matrix.architecture
  ```

### Affected Workflow:

The workflow is meant to build ISO images for multiple architectures (`x86_64`, `aarch64`), but the matrix variable (`${{ matrix.architecture }}`) is causing issues when referenced in some steps.

### Steps to Reproduce:

1. Push a commit to the `main` branch or create a pull request.
2. The GitHub Actions workflow fails on the lines where `matrix.architecture` is used.

### Expected Behavior:

The workflow should properly recognize `matrix.architecture` and successfully build ISO images for the specified architectures.

### Possible Fix:

One potential fix is to refactor the workflow to define an `ARCH` environment variable based on `matrix.architecture` and use that variable in the commands instead of directly referencing `${{ matrix.architecture }}` in the steps.

Example fix:
```yaml
- name: Setup Alpine for ${{ matrix.architecture }}
  run: |
    if [ "${{ matrix.architecture }}" == "x86_64" ]; then
      export ARCH="x86_64"
    elif [ "${{ matrix.architecture }}" == "aarch64" ]; then
      export ARCH="aarch64"
    fi
```

### To-Do:
- [ ] Investigate if all steps support `matrix` variables.
- [ ] Refactor workflow to use environment variables where necessary.
- [ ] Test the workflow after changes.

### Additional Context:

This issue occurs when using GitHub Actions to cross-compile for multiple architectures (e.g., `x86_64`, `aarch64`). The workflow needs to download binaries for each architecture and build ISO images accordingly.
